tempo:
  lower: 60
  upper: 160
  # fixed: 115
key: C
harmony:
  markov_chain:
    - [24, 35, 0, 20, 70, 5]
    - [2, 2, 5, 1, 1, 5]
    - [2, 1, 0, 1, 2, 1]
    - [39, 4, 85, 1, 13, 49]
    - [20, 86, 2, 76, 1, 39]
    - [35, 4, 8, 1, 14, 1]
melody:
  power: 1
  preferred_range:
    center: 4
    lower_offset: 3
    upper_offset: 5
  maximum_range:
    lower_offset: 4
    upper_offset: 2
  inner_drop_off: 0.04
  outer_drop_off: 0.15
  harmonic_compilance:
    - [0.94, 0.30, 0.95, 0.16, 0.87, 0.26, 0.15]  # I
    - [0.20, 0.90, 0.26, 0.86, 0.24, 0.88, 0.02]  # II
    - [0.01, 0.18, 0.87, 0.09, 0.89, 0.24, 0.83]  # III
    - [0.90, 0.26, 0.18, 0.82, 0.29, 0.99, 0.01]  # IV
    - [0.28, 0.92, 0.28, 0.27, 0.95, 0.30, 0.75]  # V
    - [0.92, 0.28, 0.85, 0.03, 0.25, 0.91, 0.20]  # VI
  dynamics: [10, 1, 3, 1, 6, 1, 3, 1, 8, 1, 3, 1, 6, 1, 3, 1]
# phrase_structure:
instruments:
  melody: Overdriven Guitar
  chord: Electric Guitar (jazz)
  bass: Electric Bass (finger)
  # rhythm:
