# test_instrument('Orchestral Harp', 'C-3', 'C-5')
# test_instrument('Violin', 'G-3', 'C-5')
# test_instrument('Viola', 'C-2', 'C-4')
# test_instrument('Cello', 'C-2', 'C-4')
# test_instrument('Contrabass', 'A-1', 'D-3')
# test_instrument('Pizzicato Strings', 'C-2', 'C-4')
