# test_instrument('SynthBrass 1', 'C-2', 'C-5')
# test_instrument('SynthBrass 2', 'C-2', 'C-5')
# test_instrument('Lead1 (square)', 'C-2', 'C-5')
# test_instrument('Lead2 (sawtooth)', 'C-2', 'C-5')
# test_instrument('Lead5 (charang)', 'C-2', 'C-5')
# test_instrument('Lead8 (bass + lead)', 'C-2', 'C-5')
# test_instrument('Pad3 (polysynth)', 'C-2', 'C-5')
# test_instrument('FX1 (rain)', 'C-2', 'C-5')
# test_instrument('FX 8 (sci-fi)', 'C-2', 'C-5')
# test_instrument('SynthStrings 1', 'C-2', 'C-4')
# test_instrument('Synth Bass 2', 'C-2', 'C-4')
# test_instrument('Lead4 (chiff)', 'C-2', 'C-4')
# test_instrument('Lead6 (voice)', 'C-2', 'C-4')
# test_instrument('Pad4 (choir)', 'C-2', 'C-4')
# test_instrument('FX 7 (echoes)', 'C-2', 'C-4')
# test_instrument('Synth Bass 1', 'A-1', 'C-3')
# test_instrument('SynthStrings 2', 'A-1', 'C-3')
# test_instrument('Synth Voice', 'A-1', 'C-3')
# test_instrument('Lead3 (calliope)', 'A-1', 'C-3')
# test_instrument('Pad2 (warm)', 'A-1', 'C-3')
# test_instrument('Pad7 (halo)', 'A-1', 'C-3')
# test_instrument('FX 4 (atmosphere)', 'A-1', 'C-3')
